### ISSUE TITLE
Python 3.13 is not supported

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [microsoft/TechExcel-Integrating-Azure-PaaS-and-AI-Services-for-AI-Design-Wins#27]
Python 3.13 requires several version updates in _requirements.txt_ as the current older versions do not have the 3.13 build wheels.

We should consider _not_ locking the versions and instead declaring _minimum_ versions, if necessary.

This is the updated file that works for Python 3.13:

```txt
# Python 3.13 required updated versions for pandas, scikit-learn, and tiktoken.
pandas==2.2.3
numpy==2.1.0
scikit-learn==1.5.2
streamlit==1.37.1
streamlit-extras==0.4.7
streamlit_js_eval==0.1.7
openai==1.42.0
azure-cognitiveservices-speech==1.40.0
azure-ai-textanalytics==5.3.0
tiktoken==0.8.0
azure-cosmos==4.7.0
```

**Comment by feaselkl** [comment]
We've held off on supporting Python 3.13 because some ML libraries have had limited support for it. We also peg requirements.txt files to specific versions to deal with issues around backwards compatibility in Python projects. Some of these projects (like openai or Semantic Kernel on the .NET side) are quite volatile and can result in the training code breaking in between deliveries due to unexpected backwards incompatibilities in new versions of libraries that learners grab.

This does come with the downside that you experienced, where some packages can become outdated for a given version of Python. I'll make the changes to the requirements file so that 3.13 users can move forward while still limiting our downside risk in sudden API changes.

Thank you for your logging of issues, by the way. I appreciate you taking the time to do that.

**Comment by simonkurtz-MSFT** [comment]
@feaselkl, thank you for making the changes! You could change _requirements.txt_ to be version-specific such as _requirements-3.13.txt_ and instruct learners to `pip install` the appropriate file. That would give you a good bit more certainty, I think. Fortunately, new Python versions only come out but once a year. =)
